app:
    resource: "@AppBundle/Controller/"
    type:     annotation
logout:
    path: /logout
#quick_estimate:
#  path:  /alliance_market/quick
#  defaults: { _controller: AppBundle:BuyBack:quickEstimate }
#accept_offer:
#    path: /alliance_market/accept
#    defaults: { _controller: AppBundle:BuyBack:acceptOffer }
