# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_provider:
            entity:
                class: AppBundle:UserEntity

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
#            form_login:
#                login_path: /login
#                check_path: /login_check
#                success_handler: authentication_handler
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - eve_sso_authenticator
            provider: db_provider

    access_control:
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/sso, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/devlogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/suggestion, roles: ROLE_USER }
        - {path: ^/pages, roles: ROLE_MEMBER }
        - {path: ^/alliance_market, roles: [ROLE_ENTITLEMENT_BUYBACK, ROLE_ENTITLEMENT_SALES] }
        - {path: ^/alliance_market/sellorders, roles: ROLE_ENTITLEMENT_BUYBACK }
        - {path: ^/alliance_market/buyorders, roles: ROLE_ENTITLEMENT_SALES }
        - {path: ^/srp, roles: ROLE_ENTITLEMENT_SRP }
        - {path: ^/admin/buy, roles: ROLE_ADMIN }
        - {path: ^/admin/sell, roles: ROLE_ADMIN }
        - {path: ^/admin/srp, roles: ROLE_ADMIN }
        - {path: ^/system/admin, roles: ROLE_SYSTEM_ADMIN }
        - {path: ^/, roles: [ROLE_USER, IS_AUTHENTICATED_REMEMBERED] }

    role_hierarchy:
        ROLE_SYSTEM_ADMIN: ROLE_TRANSACTION_ADMIN
        ROLE_TRANSACTION_ADMIN: [ROLE_BUY_ADMIN, ROLE_SELL_ADMIN, ROLE_SRP_ADMIN]
        ROLE_BUY_ADMIN: ROLE_ADMIN
        ROLE_SELL_ADMIN: ROLE_ADMIN
        ROLE_SRP_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_EDITOR
        ROLE_EDITOR: ROLE_MEMBER
        ROLE_MEMBER: ROLE_USER
        ROLE_ALLY: ROLE_USER
        ROLE_FRIEND: ROLE_USER
        ROLE_GUEST: ROLE_USER
        ROLE_OTHER1: ROLE_USER
        ROLE_OTHER2: ROLE_USER
        ROLE_OTHER3: ROLE_USER

    encoders:
        AppBundle\Entity\UserEntity:
            algorithm: bcrypt