# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    esi:
        class: EveBundle\API\ESI
        
    eve_esi:
        class: AppBundle\ESI\ESI
        arguments: ["@session"]

    eve_sso:
        class: EveBundle\API\SSO
        arguments: ['%sso_client_id%', '%sso_secret_key%']

    eve_xml_api:
        class: EveBundle\API\XML

    helper:
        class: AppBundle\Helper\Helper
        arguments: [@doctrine]

    market:
        class: AppBundle\Helper\Market
        arguments: ['@doctrine','@security.authorization_checker']

    parser:
        class: AppBundle\Helper\Parser
        arguments: ['@doctrine']

    authentication_handler:
        class: AppBundle\Helper\AuthenticationHandler
        calls:
            - [ setContainer, [ @service_container ] ]
    cache:
        class: AppBundle\Helper\Cache
        arguments: ['@doctrine', '@market']

    lineItemComparator:
        class: AppBundle\Helper\LineItemComparator
        arguments: ['@market', '@parser']

    auth_manager:
            class: AppBundle\Security\AuthorizationManager
            arguments: ['@doctrine.orm.entity_manager', '@esi', '@eve_xml_api']

    eve_sso_authenticator:
            class: AppBundle\Security\EveSSOAuthenticator
            arguments: ['@doctrine.orm.entity_manager', '@router', '@auth_manager', '@eve_sso']

    cron_tasks:
        class: AppBundle\Helper\CronTasks
        arguments: ['@doctrine', '@auth_manager']